# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nettica}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Conway"]
  s.date = %q{2010-03-30}
  s.default_executable = %q{nettica}
  s.email = %q{matt@conwaysplace.com}
  s.executables = ["nettica"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "VERSION",
     "bin/nettica",
     "doc/Nettica Bulk API Specification.doc",
     "lib/nettica.rb",
     "lib/nettica/client.rb",
     "lib/nettica/stubs/DnsApiAsmxClient.rb",
     "lib/nettica/stubs/nettica.rb",
     "lib/nettica/stubs/nettica.wsdl",
     "lib/nettica/stubs/netticaDriver.rb",
     "lib/nettica/stubs/netticaMappingRegistry.rb"
  ]
  s.homepage = %q{http://github.com/wr0ngway/nettica}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby client for managing nettica bulk-dns entries using the Nettica SOAP API}
  s.test_files = [
    "test/test_nettica.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mumboe-soap4r>, [">= 0"])
    else
      s.add_dependency(%q<mumboe-soap4r>, [">= 0"])
    end
  else
    s.add_dependency(%q<mumboe-soap4r>, [">= 0"])
  end
end

